spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5433/app_db
    username: user
    password: 123
    hikari:
      schema: app_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000